# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2021-02-12T20:22:40+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class _Shards(BaseModel):
    total: int
    successful: int
    skipped: int
    failed: int


class Total(BaseModel):
    value: int
    relation: str


class Hits(BaseModel):
    total: Total
    max_score: Any
    hits: List


class Bucket(BaseModel):
    key_as_string: str
    key: int
    doc_count: int


class Time(BaseModel):
    buckets: List[Bucket]


class Aggregations(BaseModel):
    time: Optional[Time] = None


class EightKunTimeSeries(BaseModel):
    created_key: str
    took: int
    timed_out: bool
    _shards: _Shards
    hits: Hits
    aggregations: Optional[Aggregations] = None
