# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2021-02-12T20:23:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class _Shards(BaseModel):
    total: int
    successful: int
    skipped: int
    failed: int


class Hits(BaseModel):
    total: int
    max_score: float
    hits: List


class Bucket(BaseModel):
    key_as_string: str
    key: int
    doc_count: int


class CreatedUtc(BaseModel):
    buckets: List[Bucket]


class Aggregations(BaseModel):
    created_utc: Optional[CreatedUtc] = None


class RedditTimeSeries(BaseModel):
    created_key: str
    took: int
    timed_out: bool
    _shards: _Shards
    hits: Hits
    aggregations: Optional[Aggregations] = None
