# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2021-02-12T19:53:34+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class _Shards(BaseModel):
    total: int
    successful: int
    skipped: int
    failed: int


class Total(BaseModel):
    value: int
    relation: str


class _Source(BaseModel):
    no: int
    com: str
    now: str
    name: str
    time: int
    resto: int
    board: str
    html_parsed_com: str
    h: Optional[int] = None
    w: Optional[int] = None
    ext: Optional[str] = None
    md5: Optional[str] = None
    tim: Optional[int] = None
    tnh: Optional[int] = None
    tnw: Optional[int] = None
    fsize: Optional[int] = None
    country: Optional[str] = None
    filename: Optional[str] = None
    countryname: Optional[str] = None


class Hit(BaseModel):
    _index: str
    _type: str
    _id: str
    _score: float
    _source: _Source


class Hits(BaseModel):
    total: Total
    max_score: float
    hits: List[Hit]


class FourChanContent(BaseModel):
    created_key: str
    content_key: str
    took: int
    timed_out: bool
    _shards: _Shards
    hits: Hits
