# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2021-02-12T19:57:03+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import BaseModel


class _Shards(BaseModel):
    total: int
    successful: int
    skipped: int
    failed: int


class Total(BaseModel):
    value: int
    relation: str


class _Source(BaseModel):
    v: float
    cid: str
    sub: str
    user: str
    urls: List
    score: int
    posted: str
    content: str
    deleted: bool
    lastedit: Any
    parentcid: Any
    datatype: str
    html_parsed_html: Any
    posted_formatted: str


class Hit(BaseModel):
    _index: str
    _type: str
    _id: str
    _score: float
    _source: _Source


class Hits(BaseModel):
    total: Total
    max_score: float
    hits: List[Hit]


class PoalContent(BaseModel):
    created_key: str
    content_key: str
    took: int
    timed_out: bool
    _shards: _Shards
    hits: Hits
