# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2021-02-12T19:56:16+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class _Shards(BaseModel):
    total: int
    successful: int
    skipped: int
    failed: int


class Total(BaseModel):
    value: int
    relation: str


class _Source(BaseModel):
    v: int
    html: str
    title: Optional[str] = None
    votes: Optional[int] = None
    author: str
    content: str
    timestamp: int
    datatype: str
    html_parsed_html: str
    parent: Optional[str] = None
    upvotes: Optional[int] = None
    downvotes: Optional[int] = None


class Hit(BaseModel):
    _index: str
    _type: str
    _id: str
    _score: float
    _source: _Source


class Hits(BaseModel):
    total: Total
    max_score: float
    hits: List[Hit]


class TheDonaldContent(BaseModel):
    created_key: str
    content_key: str
    took: int
    timed_out: bool
    _shards: _Shards
    hits: Hits
